/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tetris;

import java.applet.Applet;
import java.applet.AudioClip;
import java.net.URL;
import javafx.scene.paint.Color;
import javax.swing.JButton;
import javax.sound.sampled.AudioFileFormat;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/**
 *
 * @author Carlos
 */
public class tablero extends javax.swing.JFrame {
   static final int FILAS=10;
   static final int COLUMNAS=20;
   static final int TAMANO=35;
   long velocidad=1000;
   long espera=18000;
   
   
   
    /**
     * Creates new form tablero
     */

   private boolean fin=true;

    public void setFin(boolean fin) {
        this.fin = fin;
    }

    public boolean isFin() {
        return fin;
    }

   
    
    
   
        


   
   
    JButton[][]  matrizBotones = new JButton [FILAS][COLUMNAS];
    int matrizLogica[][]=new int [FILAS][COLUMNAS];
    
    
    public void generarTablero(){
        
        for(int i=0;i<FILAS;i++){
            for(int j=0;j<COLUMNAS;j++){
                matrizBotones[i][j]=new JButton();
                matrizBotones[i][j].setBackground(java.awt.Color.GRAY);
                panelTablero.add(matrizBotones[i][j]);
                matrizBotones[i][j].setVisible(true);
                 matrizBotones[i][j].setBounds(i*TAMANO, j*TAMANO, TAMANO, TAMANO);
                 matrizLogica[i][j]=0;
            }
        }
        
        
    }
    
    
    /*public void aparecer(){
        
        for(int i=0;i<FILAS;i++){
            for(int j=0;j<COLUMNAS;j++)
                switch(this.matrizLogica[i][j]){
                    case 1: this.matrizBotones[i][j].setBackground(java.awt.Color.red);
                }
        }
        
    }
*/
    
    public tablero() {
        initComponents();
    /*try
    {
      AudioClip ac=Applet.newAudioClip(new URL("file:success.wav"));
      ac.loop();
     
    }
    catch(Exception e)
    {
      System.err.println(e);
    }
       */
    }
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTablero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTableroLayout = new javax.swing.GroupLayout(panelTablero);
        panelTablero.setLayout(panelTableroLayout);
        panelTableroLayout.setHorizontalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        panelTableroLayout.setVerticalGroup(
            panelTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        
        tablero a=new tablero();
        a.setVisible(true);
        a.generarTablero();
      
        
        hiloInicio hilo=new hiloInicio(a);
       hilo.start();
 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelTablero;
    // End of variables declaration//GEN-END:variables
}
